### ISSUE TITLE
Favorite Product Event

### ISSUE THREAD

**Issue by astorm** [segmentio/analytics-magento#34]
Need to track down events for the following free/commercial extensions providing a product favorite feature

Favorite Product

    - http://www.magentocommerce.com/magento-connect/favorite-products-by-amasty.html
    - http://www.magentocommerce.com/magento-connect/ajax-bookmark-product.html
    - http://www.magentocommerce.com/magento-connect/iboughtit.html
    - http://www.magentocommerce.com/magento-connect/faves-by-plumrocket-inc.html

**Comment by sperand-io** [comment]
Tabled
