### ISSUE TITLE
Add support for Composer

### ISSUE THREAD

**Issue by 7ochem** [segmentio/analytics-magento#66]
As a Magento developer who is setting up Magento projects with Composer, I would like to have Composer support in your module.

Is this something you would like to have in your module? Can I suggest an implementation through issuing a pull request here on GitHub?

The implementation would (of course) need a `composer.json` file in the root of the repo and for implementing it within Magento, it would have a 'require' dependency on the [Magento Composer Installer](https://github.com/magento-hackathon/magento-composer-installer) en therefor also a `modman` file in the root of the repo.

**Comment by 7ochem** [comment]
@ianstormtaylor, I issued a pull request with the necessary changes to add support for Composer to the module. Could you review/respond this issue and it's pull request?

Also, as I dived in deeper into the module's code, I saw several pieces of code that could be improved. As a experienced Magento developer I could help you improve the module if you want?

**Comment by ianstormtaylor** [comment]
cc @sperand-io who can help! Help improving the module would be awesome!

**Comment by 7ochem** [comment]
Hi @sperand-io, do you need any more info for this issue/PR? The commit message states that this was untested. The truth is, that we're already using this since Feb on a live webshop. The webshop is being deployed using Composer and it is taking the Segment Analytics Magento module form my fork on GitHub which is containing this.
