### ISSUE TITLE
Customer data dump + exit showstopper

### ISSUE THREAD

**Issue by 7ochem** [segmentio/analytics-magento#68]
After login, I see a dump of the customer data and the script execution terminates (`exit()`). This is an absolute no go of course. With the module activated, no one can login on the website:

![segmentio-analytics-customer-account-dumped-data-incl-backtrace](https://cloud.githubusercontent.com/assets/2794908/6017992/901db202-ab93-11e4-8868-a2ff9fa7d1fc.png)

It traces back to the `Segment_Analytics_Helper_Data::getNormalizedCustomerInformation()` method.

**Comment by sperand-io** [comment]
Closed by #77
