### ISSUE TITLE
Instantiate action controllers through Mage::getModel to make them rewritable

### ISSUE THREAD

**Issue by 7ochem** [segmentio/analytics-magento#70]
### Instantiate action controllers through Mage::getModel to make them rewritable

For the project I'm using this module for, we have an alternative category page with a `full action name` other than `'catalog_category_view'`. So I want the `Segment_Analytics_Model_Controller_Page::_getCategoryPageHandles()` method to also return this alternative page full action name. I cannot rewrite the `Segment_Analytics_Model_Controller_Page` class through the core Magento rewrite system because in `Segment_Analytics_Model_Front_Controller` the classes are instantiated directly. Why was this done that way?

Typical rewrite I want to be able to use:

```xml
<config>
    [...]
    <global>
        <models>
            <my_segmentanalyticsextended>
                <class>My_SegmentAnalyticsExtended_Model</class>
            </my_segmentanalyticsextended>
            <segment_analytics>
                <rewrite>
                    <controller_page>My_SegmentAnalyticsExtended_Model_Controller_Page</controller_page>
                </rewrite>
            </segment_analytics>
        </models>
    </global>
    [...]
</config>
```

I'll issue a PR changing:
```php
    $class = 'Segment_Analytics_Model_Controller_' . ucwords($action->action);
    $controller = new $class;
```

Into:
```php
    $model = 'segment_analytics/controller_' . $action->action;
    $controller = Mage::getModel($model);
```

*CC: @ianstormtaylor / @sperand-io*

**Comment by 7ochem** [comment]
The pull request (#71) I issued successfully solved my problem as described in this issue. Here are some test results:

![furniture - google chrome_042](https://cloud.githubusercontent.com/assets/2794908/6042019/c9f1ef04-ac81-11e4-8448-b9fcc1bba3b0.png)

And the call to Segment appearing in the debugger:

![selection_043](https://cloud.githubusercontent.com/assets/2794908/6042097/72651aa8-ac82-11e4-9118-4545ef71753e.png)

**Comment by sperand-io** [comment]
I'm afraid I don't have the depth of magento knowledge to effectively triage this — can't confirm it won't have any negative impacts. Definitely appears to be helpful but I'm cautious about merging changes I don't fully understand as we're currently in the "lights on" stage of maintenance here.

We'll be auditing this plugin in the future which may include a rewrite and in any case will involve a 3rd party magento expert — when we do, we'll give this some thought.

Thanks so much for the report and the PR!
