### ISSUE TITLE
Why is everything sent from the client?

### ISSUE THREAD

**Issue by kevando** [segmentio/analytics-magento#82]
I use segment+intercom+magento, and I want to change how segment sends over purchased product data and it would be easier to do via the analytics-php library. So I'm curious why this extension does everything by passing json data to blocks on the client.

**Comment by sperand-io** [comment]
@kevando great question — we tend to err towards analytics.js as that affords client-side-only integrations like the conversations features of intercom and tools like facebook pixel / twitter ads. 

let me know if that makes sense!
